### ISSUE TITLE
[Fix] 수정될 사항들 처리

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#103]
## 📃 Description

다 고칩니다.

## ☑ Todo

- [x] 통계 기록이 없는 경우 "기록 없음" 렌더링
- [x] 로고 디자인 최종 버전으로 적용
- [x] 화면 최소 너비 설정 (minWidth: 1200px)
- [x] 프로필 전적 더보기 기능 추가 (20개 이상일 시 최초 20개만 렌더링)
- [x] 텍스트 입력창에서 자동완성 기능 시 배경화면이 달라지는 현상 수정
- [x] 프로필 페이지 닉네임 변경기능 추가
- [ ]
