### ISSUE TITLE
[Refactor] loader를 통해 page data fetch

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#118]
## 📃 Description

channel, direct message 등 페이지 이동시 자룔르 가져오는 경우 react-router-dom의 loader를 사용합니다.

## ☑ Todo

- [ ] channel loader 개발
- [ ] dm loader 개발
- [ ] profile loader 개발
