### ISSUE TITLE
[Feat] 채팅 관련 남은 사항들

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#120]
## 📃 Description

채팅 기능과 관련된 사항들을 개발합니다.

## ☑ Todo

- [x] 채팅방 비밀번호 해싱
- [x] 채팅방 비밀번호 전달 안함
- [x] 차단한 사용자의 메세지 처리
- [x] 퐁 게임 초대
