### ISSUE TITLE
[Chore] publish 환경 생성

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#13]
## 📃 Description

publish 환경을 생성합니다.

## ☑ Todo

- [ ] frontend, backend Dockerfile 생성
- [ ] nginx conf 및 Dockerfile생성
- [ ] docker-compose 생성
- [ ] Makefile적용
