### ISSUE TITLE
[Feat] 매치 히스토리 업데이트 구현

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#145]
## 📃 Description

매치 히스토리 업데이트 구현

## ☑ Todo

- [x] 게임이 끝났을 때, 전적이 업데이트 되어야한다.
- [x] 일반전, 랭킹전 구분해준다.
- [x] 데이터베이스에 저장 잘 되는지 확인한다
- [x] 프론트부터 동작 확인한다.
