### ISSUE TITLE
[Feat] 평가 때 사용할 전적 생성기 개발

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#149]
## 📃 Description

elo 레이팅을 반영해서 데이터베이스에 전적을 생성해봅시다.

## ☑ Todo

- [x] 전적 생성 요청 api 추가
- [x] 더미 전적 생성 코드 백엔드에 이식
- [x] elo 시스템 반영
- [x] 동작 확인
