### ISSUE TITLE
[Feat] 폰트 적용

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#154]
## 📃 Description

클러스터 맥이나 arc브라우저 등 다른 환경에서 현재 사용하고 있는 폰트를 다운받을 수 있도록 합니다.

## ☑ Todo

- [x] 현재 사용하고 있는 폰트 파악
- [x] 폰트 파일 저장
- [x] 폰트 강제 적용
