### ISSUE TITLE
[Refactor] chat socket refactoring

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#165]
## 📃 Description

chat socket을 쿠키와 라우팅에 따라 종속적으로 관리
login socket으로 사용하며 로그인할 때 초기화 할 정보 요청

## ☑ Todo

- [ ] chat socket utils로 이동
- [ ] chat socket 초기화 hooks로 이동
- [ ] chat socket 종속성 설정
- [ ] on connect 에 로그인 정보 요청, 설정
- [ ] on disconnect 에 로그인 정보 초기화
- [ ] chat socket hook 적용
- [ ] 다른 로그인 상황에서 호출되는 초기화 함수 삭제
