### ISSUE TITLE
[Bug] channel leave, kick 에서 오동작 수정

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#171]
## 📃 Description

채널을 나갈 때 콜백이 실행되지 않는 문제, 채널에서 강퇴되었을 때 필요 없는 경고(가입한 적 없는)가 뜨는 문제 수정

## ☑ Todo

- [x] leave channel 리스너 반환값 추가
- [x] 창 이동 우선 실행
- [x] 채널, DM 페이지 데이터 로드 의존성 제거
