### ISSUE TITLE
[Feat] host 변경할 수 있도록 설정

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#173]
## 📃 Description

host를 .env파일에서 변경하여 사용할 수 있도록 합니다.

## ☑ Todo

- [ ] .env에서 host 가져다 쓸 수 있도록 docker 설정
- [ ] host를 하드코딩 하는 부분 환경변수 사용하도록 변경
- [ ] domain을 사용 할 수 있는지 확인
