### ISSUE TITLE
[Bug] 발견한 이슈

### ISSUE THREAD

**Issue by Jsen27** [42ft-transcendence/transcendence#180]
## 📃 Description

- 채팅채널에서 채팅이 안되고 있음 (DB에 저장되는걸 보니 출력만 안되는듯)
- 회원가입 직후 채널입장불가 및  유저목록, 랭킹이 안보임, 프로필 렌더링시 터짐
- 프로필 페이지 렌더링 오류 현상
- 대전 신청버튼 미 동작
- 상대방 전적에서 사이드바에 있는 DM보내기 버튼 미 동작

## ☑ Todo

- [x] 채널 채팅 내역 연산 수정
- [x] chat socket의 on connect handler가 동작하지 않는 문제 수정
- [x] 회원가입 직후 채널입장불가 및  유저목록, 랭킹이 안보임, 프로필 렌더링시 터짐
- [x] 프로필 페이지 렌더링 오류 현상
- [x] 대전 신청버튼 미 동작
- [x] 상대방 전적에서 사이드바에 있는 DM보내기 버튼 미 동작
