### ISSUE TITLE
[Test] 프론트 테스트 환경 구축

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#28]
## 📃 Description

testing-library를 사용해 jest사용 및 테스트 환경 추가

## ☑ Todo

- [x] 테스팅 패키지 추가 설치
- [x] 프론트 설정 적용
- [x] 테스트 코드 추가
- [x] 동작 확인
- [x] git hooks에 동시 적용
