### ISSUE TITLE
[Chore] docker compose를 활용한 개발 환경 세팅

### ISSUE THREAD

**Issue by 42sangkkim** [42ft-transcendence/transcendence#3]
## 📃 Description

docker compose를 사용해서 프로트엔드, 백엔드의 개발 환경을 만듭니다.

## ☑ Todo

- [x] 프론트엔드 개발 환경 생성
  - [x] vite react ts 환경 생성
  - [x] Dockerfile.dev 생성
- [x] 백엔드 개발 환경 생성
  - [x] nestjs ts 환경 생성
  - [x] Dockerfile.dev 생성
- [x]  nginx 빌드 환경 생성
- [x] share 디렉토리 생성 후 기본프로필 이미지 추가
- [x] docker-compose를 활용해서 개발 환경 구성
