### ISSUE TITLE
[Feat] 🔥 서브젝트에 명시된 사항들 구현 🔥

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#41]
## 📃 Description

서브젝트에 명시된 과제들을 체크리스트로 활용하고자 합니다.

프론트, 백엔드 상관 없이 자신이 구현, 개발하려는 항목에 대해 하위 이슈로 표시해주시길 바랍니다.

미니프로젝트에서 이미 구현되었을지라도 본 프로젝트에 포함이 안되어있다면 체크하지 않았습니다.

## ☑ Todo

1. 개요
- [x] 웹사이트 백엔드는 *NestJS* 로 작성되어야 합니다.
- [x] 프론트엔드는 귀하가 선택한 *TypeScript* 프레임워크로 작성되어야 합니다.
- [x] 이 컨텍스트에서 사용하는 모든 라이브러리의 **최신 안정 버전**을 사용할 수 있습니다.
- [x] *PostgreSQL* 데이터베이스를 사용해야 합니다. 다른 데이터베이스는 허용되지 않습니다.
- [x] 귀하의 웹사이트는 [[싱글 페이지 애플리케이션](https://en.wikipedia.org/wiki/Single-page_application)](https://en.wikipedia.org/wiki/Single-page_application)이어야 합니다. 사용자는 브라우저의 뒤로/앞으로 버튼을 사용할 수 있어야 합니다.
- [ ] 귀하의 웹사이트는 *Google Chrome* 의 **최신 안정 버전**과 선택한 다른 웹 브라우저와 호환되어야 합니다.
- [ ] 사용자가 웹사이트를 탐색하는 동안 처리되지 않은 오류나 경고가 발생하지 않아야 합니다.
- [ ] 모든 것은 다음 명령으로 실행되어야 합니다: `docker-compose up --build`

2. 보안 고려 사항

완전히 동작하는 웹사이트를 만들기 위해 다음과 같은 몇 가지 보안 고려 사항에 대처해야 합니다:

- [x] #65
- [x] #69
- [ ] 웹사이트는 *SQL injection* 에 대한 보호가 필요합니다.
- [x] Form 및 사용자 입력에 대해 서버 측에서 유효성 검사를 구현해야 합니다.
- [x] 명백한 보안상의 이유로 자격증명, API 키, 환경 변수 등은 로컬 .env 파일에 저장하고 git에서 무시해야 합니다.

3. 사용자 계정

- [x] 사용자는 42 인트라의 OAuth 시스템을 사용하여 로그인해야 합니다.
- [x] 사용자는 웹사이트에서 표시될 고유한 이름을 선택할 수 있어야 합니다.
- [x] 사용자는 아바타를 업로드할 수 있어야 합니다. 사용자가 아바타를 업로드하지 않으면 기본 아바타가 설정되어야 합니다.
- [x] #90 
- [x] 사용자는 다른 사용자를 친구로 추가하고, 상대방의 현재 상태(온라인, 오프라인, 게임 중 등)를 볼 수 있어야 합니다.
- [x] 승리 및 패배, 레더 레벨, 업적 등과 같은 통계 정보는 사용자 프로필에 표시되어야 합니다.
- [x] 각 사용자는 1대1 게임, 레더 등을 포함한 **경기 기록**을 가지고 있어야 하며, 로그인한 모든 사용자가 이를 조회할 수 있어야 합니다.

4. 채팅

사용자들을 위해 채팅 기능을 구현해야 합니다:

- [x] 사용자는 공개, 비공개 또는 암호로 보호되는 **채널**(채팅방)을 생성할 수 있어야 합니다.
- [x] #78
- [x] 사용자는 다른 사용자를 차단할 수 있어야 합니다. 이렇게 하면 차단한 계정으로부터 더 이상 메시지를 받지 않게 됩니다.
- [x] 새로운 채널을 생성한 사용자는 자동으로 **채널 소유자**로 설정되며, 채널을 나가기 전까지 소유자로 남습니다.
- [x] #75
- [x] #76
- [x] #77
- [x] 사용자는 채팅 인터페이스를 통해 다른 사용자를 Pong 게임으로 초대할 수 있어야 합니다.
- [x] 사용자는 채팅 인터페이스를 통해 다른 플레이어의 프로필에 접근할 수 있어야 합니다.

5. 게임

이 웹사이트의 주요 목적은 다른 플레이어와 Pong 게임을 플레이하는 것입니다.

- [x] #70
- [x] #139
- [x] #72
- [x] #73
- [x] #74
