### ISSUE TITLE
[Refactor] 사이드바 리팩토링 및 재개발 

### ISSUE THREAD

**Issue by chanwoong1** [42ft-transcendence/transcendence#45]
## 📃 Description

사이드바를 동적으로 사용하기 위해 다음과 같은 구조로 다시 만들어보고자 합니다.

미니 프로젝트에서의 사이드바는 각각의 페이지에서 사이드바에 대한 요소들이 담겨서 가독성이 떨어진다는 단점이 있었습니다.

본 프로젝트에서는 각 페이지의 url_path에 따라 사이드바를 자동적으로 렌더링해줄 수 있도록 변경하고자 합니다.

## 구현 목표 및 과정

1. 컴포넌트화

컴포넌트화로 각 페이지 및 탭에 필요한 사이드바를 개별적으로 구현합니다.

2. 사이드바 구성 정보 설정
```
const sidebarConfig = {
  '/channel-list': <ChannelSidebar />,
  '/game-list': <GameSidebar />,
  '/ranking': <RankingSidebar />,
  // ...
};
```

위와 같이 페이지의 주소별로 렌더링해줄 사이드바를 각각 매핑합니다.

3. 동적 렌더링
```
const currentRoute = window.location.pathname;
const CurrentSidebar = sidebarConfig[currentRoute];
```

각 페이지의 라우트를 기준으로 사이드바를 동적으로 렌더링합니다.

이 방식은 향후에 변경될 수 있습니다. (같은 채널 라우트더라도 사이드바가 달라질 수 있으므로)

4. 컨텍스트 및 상태 관리

사이드바 내에서 복잡한 상태 관리가 필요한 경우, React Context나 recoil을 사용하여 중앙에서 상태를 관리하고, 필요한 컴포넌트로 상태를 전달합니다.

5. 스타일링

사이드바의 스타일을 적용합니다.

여기까지는 구현 필수 목표이고 아래는 향후 최적화 시 해줄만한 요소들입니다.

6. 퍼포먼스 최적화

React.memo나 useMemo를 활용하여 불필요한 렌더링을 최소화하며, React.lazy와 Suspense를 사용하여 코드 분할을 구현하여 퍼포먼스를 최적화할 수 있습니다.

## ☑ Todo

- [x] 컴포넌트화
- [x] 사이드바 구성 정보 설정
- [x] 동적 렌더링
- [x] 컨텍스트 및 상태 관리
- [x] profile, 전적 페이지에 관한 사이드바 개발
- [x] 유저 목록 페이지 사이드바 개발
- [x] ranking 페이지 사이드바 개발
- [x] game-list 페이지 사이드바 개발
- [x] 스타일링
- [x] 동작 확인
