### ISSUE TITLE
[Feat] channel-list 페이지 개발

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#46]
## 📃 Description

채널 목록을 보여주는 페이지를 개발합니다

## ☑ Todo

- [ ] Channel Search Item 개발
- [ ] Search List 개발
- [ ] Channel List Page View개발
- [ ] Channel List Page Container 개발
