### ISSUE TITLE
[Feat] 페이지 제목 및 favicon 적용

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#56]
## 📃 Description

탭 목록 영역에서 제목과 아이콘을 적용합니다.

## ☑ Todo

- [ ] favicon 이미지 적용
- [ ] favicon 디렉토리 nginx에 마운트
- [ ] nginx에 favicon 라우팅 설정
- [ ] index.html에 Title 및 favicon 설정
