### ISSUE TITLE
[Feat] 채널 생성, 참가 모달 구현

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#68]
## 📃 Description

채널을 생성하거나 참가하는 모달을 구현합니다.

## ☑ Todo

- [x] 채널 생성 모달 구현
- [x] 채널 참가 모달 구현
- [x] chatting 페이지 요소에  모달 적용
