### ISSUE TITLE
[Feat] 채널 페이지, DM 페이지 제작

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#80]
## 📃 Description

channel, dm페이지에 필요한 기능과 컴포넌트를 제작하고 페이지를 추가합니다.

## ☑ Todo

- [x] chat bubble 컴포넌트 추가
- [x] chat item 컴포넌트 추가
- [x] chat list 컴포넌트 추가
- [x] channel에 필요한 atom, selector 추가
- [x] dm 에 필요한 atom, selector 추가
- [x] chat socket event listener 추가
- [x] channel page 추가
- [x] dm page 추가
