### ISSUE TITLE
[Design] 디자인 수정

### ISSUE THREAD

**Issue by sang-kyeong** [42ft-transcendence/transcendence#88]
## 📃 Description

현재 디자인 중 의도와 다른 것 수정

## ☑ Todo

- [x] App.tsx에서 컴마 제거
- [x] nav bar, side bar에 flex-shrink 추가하여 사이즈 고정
- [x] side bar 위에서부터 내려오게 수정
